version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521:xe
      - SPRING_DATASOURCE_USERNAME=C##Cloud_Native
      - SPRING_DATASOURCE_PASSWORD=your_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - oracle-db

  oracle-db:
    image: gvenzl/oracle-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=your_password
      - ORACLE_ALLOW_REMOTE=true
    volumes:
      - ./init-user.sql:/docker-entrypoint-initdb.d/init-user.sql
